name: Testing

on: push

jobs:
  publish-to-testpypi1:
    name: blah
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Please Work 1
      run: echo "let's see what happens"
      
  publish-to-testpypi2:
    if: startsWith(github.ref, "refs/tags/v*")  # only publish to PyPI on tag pushes
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Please Work 2
      run: echo "let's see what happens2"
