name: Testing

on: push

jobs:
  publish-to-testpypi:
    if: startsWith(github.ref, 'refs/tags/v*')  # only publish to PyPI on tag pushes
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest

    steps:

    - name: Please Work 1
      run: echo "let's see what happens"
